Sport shoes store pull request
Lkupybida/lab_5 pull request #1
Opened 2022-12-12 08:07 UTC by Lkupybida

added code and gitignore

2022-12-18 10:17 UTC, bogdan9876 requested changes
між деякими методами є пробіл , а між іншими немає

2022-12-18 10:17 UTC, bogdan9876 commented on main.cpp
> +#include "string.h"
space before using namespace std

2022-12-18 10:17 UTC, bogdan9876 commented on main.cpp
> +private:
the first public, the second protected, the third private

2022-12-18 10:17 UTC, bogdan9876 commented on main.cpp
> +private:
the first public, the second protected, the third private

2022-12-21 18:38 UTC, bogdan9876 approved these changes

2022-12-21 18:39 UTC, bogdan9876 approved these changes

2022-12-22 09:14 UTC, merged

2023-02-22 22:00 UTC, zveres-ss commented on main.cpp
> +    Sneakers array[2];
2 is magic variable, make it as constant